### PR TITLE
fix: preserve field names in the first row

### LINKED ISSUE #1087: A moment of nothing
The following code:

https://github.com/googleapis/sloth/blob/5aabbbee0e13cc687dfbc249e6979f83a518894a/src/exportToSheets.ts#L79-L82

https://github.com/googleapis/sloth/blob/5aabbbee0e13cc687dfbc249e6979f83a518894a/src/fetchServices.ts#L171-L174

are completely wipe the spreadsheet and there is a moment of nothing.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #1087

This is still ugly, but it won't break the internal datastudio, I think.

### CODE REVIEW

File: src/fetchServices.ts [hunk 1]
```diff
@@ -167,10 +167,11 @@ export async function exportApisToSheets() {
   const values = await getResults();
   values.unshift(['Service', 'Title', 'Group', 'HasSurface', 'InScope', 'ToS']);
```
Comment (bcoe) [inline src/fetchServices.ts:168]: won't this lead to the first column being added multiple times, since we're no longer clearing A1?

**Review by bcoe — CHANGES_REQUESTED** [review]

File: src/fetchServices.ts (hunk 1 above)
Comment (tmatsuo) [reply src/fetchServices.ts:168]: I think it will override

**Review by bcoe — APPROVED** [review]
